### ISSUE TITLE
urls with query strings not supported.

### ISSUE THREAD

**Issue by jdalton** [mjackson/npm-http-server#44]
I tried to load in a page:
```
https://npmcdn.com/font-awesome@4.6.3/css/font-awesome.min.css
```
and it tries to load:
```
https://npmcdn.com/font-awesome@4.6.3/fonts/fontawesome-webfont.woff?v=4.6.3
```
which results in:
```
Invalid URL: /font-awesome@4.6.3/fonts/fontawesome-webfont.woff?v=4.6.3
```

It works with 
```js
https://cdn.jsdelivr.net/fontawesome/4.6.3/css/font-awesome.min.css
```

**Comment by nkbt** [comment]
I reckon query params are stripped off entirely.

**Comment by mjackson** [comment]
Huh, that's interesting. font-awesome is probably using that query parameter to bust the cache, not realizing that it's already being loaded from a URL with the version number already in it.

This is documented behavior, BTW. From npmcdn.com:

> All other query parameters are invalid and will result in a 403 Forbidden response. This helps preserve the integrity of the cache for URLs with valid query strings.

Maybe we should make an exception for the `v` query parameter? Or maybe we could convince the font-awesome people to not abuse query strings for busting the cache?

**Comment by jdalton** [comment]
Ran into this issue as well adding cache-busting to service worker fetches. Others like rawgit, jsdelivr, cdnjs seem to be ok with the query param.

**Comment by mjackson** [comment]
What I'm trying to avoid is people who add the timestamp to the query string like `?_=43523452345`. URLs like that are un-cacheable.

**Comment by mjackson** [comment]
It should be easy enough to write an exception for `?v=4.6.3`. I just wonder how many of these kinds of exceptions we'll eventually need.

**Comment by jdalton** [comment]
> What I'm trying to avoid is people who add the timestamp to the query string like ?_=43523452345. URLs like that are un-cacheable.

Maybe ping the other cdn folks to see how they handle it. Tracking a list of query params seems like a headache. \@megawac

**Comment by mjackson** [comment]
Other option would be to ignore query strings entirely at the CDN level (query string has no effect on caching, delivers the same file regardless). This would mean deprecating our existing query parameters which I don't think a lot of people use anyway.

/cc @ggoodman I know you're the main person using the `?json` query parameter. Maybe we could put something in the pathname instead? Something like `npmcdn.com/__json__/package@version/file`. Would that work for you?

/cc @mbostock Are you using the `main` query parameter? Or are the defaults working fine for you now?

**Comment by ggoodman** [comment]
I'm fine with a path change. I just need a head's up if and when it goes
live.

**Comment by mbostock** [comment]
I am not personally using it. It sounds like a fine change to me.

**Comment by jdalton** [comment]
Ignoring the params may be what others do *(sounds right at least)*.

**Comment by mjackson** [comment]
@ggoodman Are you using query params on static files? Or just directories?

e.g. are you making requests like:

    GET /history@3.0.0/umd/history.min.js?json

or like this

    GET /history@3.0.0/umd/?json

?

**Comment by mjackson** [comment]
@ggoodman The reason I ask is because I'd like to remove support for using query strings on [static content](https://support.cloudflare.com/hc/en-us/articles/200172516-Which-file-extensions-does-CloudFlare-cache-for-static-content-). That should address @jdalton's issue here. We can keep using `/?json` for directories though.

**Comment by mjackson** [comment]
@ggoodman Based on your original PR (#36) it looks like you're only ever sending requests for metadata to directory paths. I think I added support for individual file paths for the sake of completeness. But now I wanna remove it! Haha, that's what I get for creating a feature nobody asked for :P

**Comment by mjackson** [comment]
ok @jdalton, this is now fixed. I made a tweak at the CDN level that prevents query strings from being forwarded on to the origin server when requesting static content.

Enjoy :)

**Comment by jdalton** [comment]
Thank you!

**Comment by ggoodman** [comment]
Didn't break me. @mjackson 👍

**Comment by jdalton** [comment]
Heads up
https://npmcdn.com/font-awesome@4.6.3/fonts/fontawesome-webfont.woff?v=4.6.3
and
https://unpkg.com/font-awesome@4.6.3/fonts/fontawesome-webfont.woff2?v=4.6.3
are still failing

**Comment by mjackson** [comment]
Whoops. I accidentally screwed up the CDN settings. Both of those URLs work again, @jdalton!

Maybe it's time I developed a set of regression tests against the actual CDN...

**Comment by jdalton** [comment]
:metal: Doubley thank you!
